In [5]:
import numpy as np

In [7]:
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
mat.sum(axis=0)

array([ 9, 12, 15])

In [9]:
mat.sum(axis=1)

array([ 3, 12, 21])

In [10]:
np.sort(np.random.randn(10))

array([-2.68245892, -1.02816635, -1.00459716, -0.44416426, -0.02078358,
        0.10348391,  0.23603471,  0.28785092,  0.92046307,  1.67766655])

In [11]:
np.linspace(0,0.3,num=20)

array([0.        , 0.01578947, 0.03157895, 0.04736842, 0.06315789,
       0.07894737, 0.09473684, 0.11052632, 0.12631579, 0.14210526,
       0.15789474, 0.17368421, 0.18947368, 0.20526316, 0.22105263,
       0.23684211, 0.25263158, 0.26842105, 0.28421053, 0.3       ])

In [12]:
temp = np.array([1,2,3,1,2,3,1,2,3]).reshape(3,3)
b_filt = temp>=2
temp[b_filt]

array([2, 3, 2, 3, 2, 3])

In [15]:
import os
print(os.getcwd())

c:\Users\sanik\OneDrive\Desktop\cdac


In [14]:
os.chdir("../")

In [17]:
__file__ = "Computer Networks"
print(os.path.realpath(__file__))

C:\Users\sanik\OneDrive\Desktop\cdac\Computer Networks


In [22]:

print(os.path.dirname(os.path.realpath(__file__)))

C:\Users\sanik\OneDrive\Desktop\cdac


In [23]:
path =  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'DIR_created_from_code')
print("Creating a directory at " , path)
os.mkdir(path) 

Creating a directory at  C:\Users\sanik\OneDrive\Desktop\cdac\DIR_created_from_code


In [24]:
path =  os.path.join(os.path.dirname(os.path.realpath(__file__)), 'DIR_created_from_code\level1\level2')
print("Creating a directory at " , path)

Creating a directory at  C:\Users\sanik\OneDrive\Desktop\cdac\DIR_created_from_code\level1\level2


In [25]:
os.makedirs(path) 

path = os.chdir('../../../')
dir_list = os.listdir(path)
print("Files and directories in '", path, "' :" , dir_list) 

Files and directories in ' None ' : ['.3T', '.android', '.bash_history', '.cache', '.config', '.dbshell', '.dlv', '.eclipse', '.gitconfig', '.ipython', '.lesshst', '.mongorc.js', '.p2', '.packettracer', '.ssh', '.vscode', '.vscode-cli', '.vuerc', 'algs4', 'AppData', 'Application Data', 'Cisco Packet Tracer 8.2.1', 'Contacts', 'Cookies', 'day2', 'db', 'db.json', 'demo', 'Documents', 'Downloads', 'eclipse-workspace', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'menu-card', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{bbe4e322-b6cd-11ed-8b22-aa7ec08a8c9f}.TM.blf', 'NTUSER.DAT{bbe4e322-b6cd-11ed-8b22-aa7ec08a8c9f}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{bbe4e322-b6cd-11ed-8b22-aa7ec08a8c9f}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'package-lock.json', 'package.json', 'PrintHood', 'Recent', 'rest-app', 'rest-app.zip', 'router-app', 'Saved Games', 'Searches', 'SendTo',